name: my_first_workflow
on: [push]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
      uses: actions/checkout@v3
      - name: say hi
      run: echo "Hello, my first workflow!"
