name: my_first_workflow
on:
  push:
    branches-ignore:
      - 'release'
jobs:
  first_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: say hi
        run: echo "Hello, my first workflow!"
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: check project location
        run: echo $GITHUB_WORKSPACE
  second_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.branch == 'main'
    steps:
      - name: stuff
        run: flake8 . --count
      - name: check coverage
        run: |
          coverage run -m pytest
          coverage report
